services:
  - type: web
    name: chesstise-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: frankfurt
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: chesstise-db
          property: connectionString
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: chesstise-api
      - key: Jwt__Audience
        value: chesstise-app
      - key: Jwt__ExpiryHours
        value: "72"
      - key: Google__ClientId
        sync: false
      - key: Groq__ApiKey
        sync: false
    healthCheckPath: /api/health

databases:
  - name: chesstise-db
    region: frankfurt
    plan: free
    databaseName: chesstise
    user: chesstise
